#!/usr/bin/env bash
# Fetch the two shared libraries the `ocr` feature loads at runtime.
#
# pdf-inspector links neither of them: PDFium rasterizes pages and ONNX Runtime
# executes the PP-OCRv6 Small model, and both are opened with dlopen() the
# first time OCR runs. This script drops pinned builds into vendor/ and writes
# vendor/ocr-env.sh with the environment variables that point at them.
#
# The model weights are NOT fetched here — pdf-inspector downloads and
# checksum-verifies those into its own cache on the first OCR run.
set -euo pipefail

PDFIUM_TAG="${PDFIUM_TAG:-chromium/8021}"
ONNXRUNTIME_VERSION="${ONNXRUNTIME_VERSION:-1.29.0}"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
vendor="$repo_root/vendor"

case "$(uname -s)" in
    Darwin) os=mac; ort_os=osx; libext=dylib ;;
    Linux)  os=linux; ort_os=linux; libext=so ;;
    *) echo "unsupported OS $(uname -s); fetch PDFium and ONNX Runtime by hand" >&2; exit 1 ;;
esac
case "$(uname -m)" in
    arm64|aarch64) pdfium_arch=arm64; ort_arch=arm64 ;;
    x86_64) pdfium_arch=x64; ort_arch=x64 ;;
    *) echo "unsupported architecture $(uname -m)" >&2; exit 1 ;;
esac

mkdir -p "$vendor"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

echo "==> PDFium $PDFIUM_TAG ($os-$pdfium_arch)"
curl -fsSL -o "$tmp/pdfium.tgz" \
    "https://github.com/bblanchon/pdfium-binaries/releases/download/${PDFIUM_TAG}/pdfium-${os}-${pdfium_arch}.tgz"
rm -rf "$vendor/pdfium"
mkdir -p "$vendor/pdfium"
tar -xzf "$tmp/pdfium.tgz" -C "$vendor/pdfium"

echo "==> ONNX Runtime $ONNXRUNTIME_VERSION ($ort_os-$ort_arch)"
ort_dir="onnxruntime-${ort_os}-${ort_arch}-${ONNXRUNTIME_VERSION}"
curl -fsSL -o "$tmp/onnxruntime.tgz" \
    "https://github.com/microsoft/onnxruntime/releases/download/v${ONNXRUNTIME_VERSION}/${ort_dir}.tgz"
rm -rf "$vendor/onnxruntime"
tar -xzf "$tmp/onnxruntime.tgz" -C "$tmp"
mv "$tmp/$ort_dir" "$vendor/onnxruntime"

pdfium_lib="$vendor/pdfium/lib/libpdfium.$libext"
ort_lib="$(ls "$vendor"/onnxruntime/lib/libonnxruntime.$libext "$vendor"/onnxruntime/lib/libonnxruntime.*.$libext 2>/dev/null | head -1)"
for lib in "$pdfium_lib" "$ort_lib"; do
    [ -f "$lib" ] || { echo "expected library missing: $lib" >&2; exit 1; }
done

# Gatekeeper quarantines anything curl downloads, and a quarantined dylib
# fails to dlopen with an opaque error.
if [ "$os" = mac ]; then
    xattr -dr com.apple.quarantine "$vendor" 2>/dev/null || true
fi

cat > "$vendor/ocr-env.sh" <<ENV
# Generated by scripts/fetch-ocr-runtime.sh — source this before running with --ocr.
export PDFIUM_LIB_PATH="$pdfium_lib"
export ORT_DYLIB_PATH="$ort_lib"
ENV

echo
echo "PDFium:       $pdfium_lib"
echo "ONNX Runtime: $ort_lib"
echo
echo "Next:  source vendor/ocr-env.sh"
